# Note: this environment will be merged with the pangeo-notebook/environment.yml
# by conda-lock. Only put things here that are not already in pangeo-notebook
name: pangeo
channels:
 - conda-forge
 - defaults
dependencies:
 - conda-forge/linux-64::cupy
 # Using defaults channel for GPU support https://github.com/pangeo-data/pangeo-docker-images/issues/243
 - pkgs/main/linux-64::tensorflow-gpu>=2
 - jax
