[workspace]
authors = ["Manon Rousseau <manon.rousseau.external@cnes.fr>"]
channels = ["conda-forge", "nodefaults"]
name = "environment"
platforms = ["linux-64"]
version = "0.1.0"



[tasks]

[dependencies]

[feature.base-notebook]
channels = ["conda-forge", "nodefaults"]

[feature.base-notebook.dependencies]
python = "3.13.*"
pangeo-notebook = "2026.6.3.*"
pip = "*"

[feature.base-notebook.pypi-dependencies]
jupyter-launcher-shortcuts = "*"

[feature.pangeo-notebook]
channels = ["conda-forge", "nodefaults"]

[feature.pangeo-notebook.dependencies]
adlfs = "*"
argopy = "<1.4.0"
awscli = "*"
black = "*"
boto3 = "*"
bottleneck = "*"
cartopy = "*"
cdsapi = "*"
cfgrib = "*"
cf_xarray = "*"
ciso = "*"
cmocean = "*"
contextily = "*"
dask-geopandas = "*"
dask-ml = "*"
datashader = "*"
descartes = "*"
duckdb-cli = "*"
earthaccess = "*"
eodag = "*"
eofs = "*"
erddapy = "*"
esmpy = "*"
fastjmd95 = "*"
flox = "*"
fsspec = "*"
gcm_filters = "*"
gcsfs = ">=2025"
gdal = "*"
gh = "*"
gh-scoped-creds = "*"
geocube = "*"
geopandas = "*"
geopy = "*"
geoviews-core = "*"
git-lfs = "*"
google-cloud-sdk = "*"
gsw = "*"
h5netcdf = "*"
h5py = "*"
holoviews = "*"
hvplot = "*"
icechunk = ">=2"
intake = "*"
intake-esm = "*"
intake-geopandas = "*"
intake-stac = "*"
intake-xarray = "*"
ipdb = "*"
ipykernel = "*"
ipyleaflet = "*"
ipympl = "*"
ipytree = "*"
ipywidgets = "*"
jupyterlab_code_formatter = "*"
jupyterlab-git = "*"
jupyterlab-lsp = "*"
jupyterlab-myst = "*"
jupyter-panel-proxy = "*"
jupyter-resource-usage = "*"
jupyter-sshd-proxy = "*"
kerchunk = "*"
libgdal-arrow-parquet = "*"
libgdal-netcdf = "*"
line_profiler = "*"
lonboard = "*"
lxml = "*"
lz4 = "*"
matplotlib-base = "*"
memory_profiler = "*"
metpy = "*"
nb_conda_kernels = "*"
nbstripout = "*"
nc-time-axis = "*"
netcdf4 = "*"
numbagg = "*"
numcodecs = "*"
numpy = ">=2.0.0"
numpy_groupies = "*"
obstore = "*"
odc-stac = ">=0.4.0"
openssh = "*"
pandas = "<3"
panel = "*"
param = "*"
planetary-computer = "*"
pop-tools = "*"
pot = "*"
pyarrow = "*"
pycamhd = "*"
pydap = "*"
pystac = "*"
pystac-client = "*"
python-blosc = "*"
python-duckdb = "*"
python-gist = "*"
python-graphviz = "*"
python-lsp-ruff = "*"
python-xxhash = "*"
qgis = "*"
rasterio = "*"
rclone = "*"
rechunker = "*"
rio-cogeo = "*"
rioxarray = "*"
ruff = "*"
s3fs = "*"
satpy = "*"
scikit-image = "*"
scikit-learn = "*"
scipy = "*"
seaborn = "*"
sparse = "*"
snakeviz = "*"
stackstac = "*"
tiledb-py = "*"
timezonefinder = "*"
virtualizarr = "*"
watermark = "*"
xarray = "*"
xarrayutils = "*"
xarray_leaflet = "*"
xarray-spatial = "*"
xbatcher = "*"
xclim = "*"
xesmf = "*"
xgboost = "*"
xgcm = "*"
xhistogram = "*"
xmip = "*"
xmitgcm = "*"
xpublish = "*"
xrft = "*"
xskillscore = "*"
xxhash = "*"
xvec = "*"
zarr = ">=3.1.6"

[feature.pytorch-notebook]
channels = ["conda-forge", "nodefaults"]

[feature.pytorch-notebook.dependencies]
cuda-version = ">=12.0"
jupyterlab-nvdashboard = "*"
gpytorch = "*"
pytorch = "*"
tensorboard = "*"
torchvision = ">=0.26.0"
torchgeo = "*"

[feature.pytorch-notebook.pypi-dependencies]
tensorflow = "<2.21"

[environments]
base-notebook = ["base-notebook"]
pangeo-notebook = ["base-notebook", "pangeo-notebook"]
pytorch-notebook = ["base-notebook", "pangeo-notebook", "pytorch-notebook"]
