#!/usr/bin/env python3
"""
Generate human readable packages.txt file from a conda-lock file.
"""
import argparse
import yaml

def parse_lock_line(line):
    """
    Parse a single conda-lock line and return name

    Supports both conda and pip pins.

    Returns name of package and version as tuple
    """

    if 'conda' in line:
        pkg_name, version, _ = line['conda'].split("/")[-1].strip(".conda").rsplit('-', 2)
        print(pkg_name,version)
    elif 'pypi' in line:
        filename = line["pypi"].split('/')[-1]
        if filename.endswith('.whl'):
            # Wheels are in the format <package-name>-<version>-<tags>
            underscored_pkg_name, version, _ = filename.split('-', 2)
        elif filename.endswith('.tar.gz'):
            # tarballs are just <package>-<version_.tgz
            basename = filename.rsplit('.', 2)[0]
            underscored_pkg_name, version = basename.split('-', 1)
        else:
            raise RuntimeError(f'Found unknown file {filename} in pixi-lock file')

        # PyPI has files with '_' when the package name has '-' in it
        pkg_name = underscored_pkg_name.replace('_', '-')
    else:
        print("package not recognize")
        print(package)

    return pkg_name, version

def main():
    argparser = argparse.ArgumentParser()
    argparser.add_argument('lock_file', help='Path to pixi.lock file to parse', default='pixi.lock')
    argparser.add_argument('--environment', help='Name of the environment to parse', default='base-notebook')
    argparser.add_argument('--arch', help='Name of the selected architecture', default='linux-64')
    args = argparser.parse_args()

    with open(args.lock_file) as stream:
        try:
            lock = yaml.safe_load(stream)
        except yaml.YAMLError as exc:
            print(exc)

    print('# List of packages and versions installed in the environment')
    print(f'# Generated by parsing {args.lock_file}, please use that as source of truth')
    for line in lock['environments'][args.environment]['packages'][args.arch]:
        pkg_name, version = parse_lock_line(line)
        print(f'{pkg_name}=={version}')

if __name__ == '__main__':
    main()

