name: notebook
channels:
  - conda-forge
dependencies:
  # TODO: turn into conda metapackage
  - dask
  - dask-gateway
  - dask-kubernetes
  - dask-labextension
  - distributed
  - jupyterhub
  - jupyterlab
  - jupyter-server-proxy
  - nbgitpuller
  - nomkl
  - python-graphviz
  - pip
  # Additional Packages (alphabetical)
  - python=3.7
  - cartopy
  - dask-ml
  - datashader
  - fsspec
  - gcsfs
  - geopandas
  - geoviews-core
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-esm=2019
  - intake-stac
  - intake-xarray
  - ipyleaflet
  - jupyter-panel-proxy
  - lz4
  - matplotlib-base
  - numpy
  - pandas
  - panel
  - rasterio
  - s3fs
  - sat-search
  - sat-stac
  - satpy
  - scikit-image
  - scikit-learn
  - scipy
  - xarray
  - zarr
