name: notebook
channels:
  - conda-forge
dependencies:
  # TODO: turn into conda metapackage
  - bokeh=1.4
  - dask=2.11
  - dask-gateway=0.6
  - dask-kubernetes=0.10
  - dask-labextension=1.1
  - distributed=2.11
  - jupyterhub=1.1
  - jupyterlab=1.2
  - jupyter-server-proxy=1.2
  - nbgitpuller=0.8
  - python-graphviz=0.13
  - pip=20.0
  - tornado=6
  # Additional Packages (alphabetical)
  - python=3.8
  - cartopy=0
  - cupy=7
  - dask-ml=0
  - datashader=0
  - fsspec=0
  - gcsfs=0
  - geopandas=0
  - geoviews-core=1
  - h5netcdf=0
  - h5py=2
  - holoviews=1
  - hvplot=0
  - intake=0
  - intake-esm=2019
  - intake-stac=0
  - intake-xarray=0
  - ipyleaflet=0
  - jupyterlab-nvdashboard=0
  - jupyter-panel-proxy=0
  - keras-gpu=2
  - lz4=3
  - matplotlib-base=3
  - numpy=1
  - pandas=1
  - panel=0
  - pytorch-cpu=1
  - rasterio=1
  - s3fs=0
  - sat-search=0
  - sat-stac=0
  - satpy=0
  - scikit-image=0
  - scikit-learn=0
  - scipy=1
  - tensorflow-gpu=2
  - xarray=0
  - zarr=2
