name: notebook
channels:
  - conda-forge
dependencies:
  # TODO: turn into conda metapackage
  - python=3.7
  - dask
  - dask-gateway
  - dask-kubernetes
  - dask-labextension
  - distributed
  - jupyterhub
  - jupyterlab
  - jupyter-server-proxy
  - nbgitpuller
  - nomkl
  - python-graphviz
  - pip
