# Note: this environment will be merged with the pangeo-notebook/environment.yml
# by conda-lock. Only put things here that are not already in pangeo-notebook
name: pytorch-notebook
channels:
  - conda-forge
  - nodefaults
dependencies:
 - cuda-version>=12.0
 - jupyterlab-nvdashboard
 - gpytorch
 - pytorch
 - tensorboard
 - torchvision>=0.26.0
 - torchgeo
 - python>=3.12,<3.13
 - pip:
    - tensorflow<2.21