# Only test building image
name: PullRequestBuild

on:
  pull_request:
    branches:
      - staging

env:
  GITHUB_REF: ${{ github.ref }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE_PREFIX: pangeodev/

jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE: [base-image, pangeo-image]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Sync base-config files without overwriting
      run: |
        rsync -a -v --ignore-existing base-image/* ${{ matrix.IMAGE }}/

    - name: Build Image
      run: |
        cd ${{ matrix.IMAGE }}
        docker build --rm --cache-from pangeodev/${{ matrix.IMAGE }}:latest -t pangeodev/${{ matrix.IMAGE }}:PR .
  #    - name: Test Image
  #      run: |
  #        docker run ${IMAGE_SPEC} binder/verify
  #        docker run ${ONBUILD_IMAGE_SPEC} binder/verify
    - name: Display All Conda Packages
      run: |
        docker run pangeodev/${{ matrix.IMAGE }}:PR conda list
