# Just re-tag latest staging image
# NOTE: not implemented yet...
name: Publish Prod
on:
  push:
    branches:
      - prod
jobs:
  base-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
