# Re-tag most recent staging image with github tag and latest
name: Production
on:
  push:
    tags:
    - '*'

env:
  DOCKER_ORG: pangeodev
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE: [base-image, base-worker, base-notebook, pangeo-worker, pangeo-notebook]
    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Job Environment Variables
      run: |
        CALVER="$( date -u '+%Y.%m.%d' )"
        SHA7="${GITHUB_SHA::7}"
        TAG="${GITHUB_REF##*/}"
        DOCKER_TAG=$TAG
        IMAGE_SPEC="${DOCKER_ORG}/${{ matrix.IMAGE }}:${DOCKER_TAG}"
        echo "::set-env name=DOCKER_TAG::${DOCKER_TAG}"
        echo "::set-env name=IMAGE_SPEC::${IMAGE_SPEC}"

    - name: Pull Latest Master Image
      run: |
        docker pull ${DOCKER_ORG}/${{ matrix.IMAGE }}:master

    - name: Authenticate with DockerHub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

    - name: Retag and Push Image
      run: |
        IMAGE_LATEST=${DOCKER_ORG}/${{ matrix.IMAGE }}:latest
        docker tag ${DOCKER_ORG}/${{ matrix.IMAGE }}:master $IMAGE_SPEC
        docker tag ${DOCKER_ORG}/${{ matrix.IMAGE }}:master $IMAGE_LATEST
        docker push $IMAGE_LATEST
        docker push $IMAGE_SPEC
