# Just re-tag latest staging image
# NOTE: not implemented yet...
name: ProductionBuild
on:
  push:
    branches:
      - prod
jobs:
  base-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
