# Check for new versions of pangeo-notebook metapackage on Conda Forge
name: WatchCondaForge

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: github.repository == 'pangeo-data/pangeo-stacks-dev'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get latest pangeo-notebook version
        id: latest_version
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.1
        with:
          org: "conda-forge"
          package: "pangeo-notebook"

      - name: Find and Replace Base
        uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          include: "*-notebook/environment.yml"
          find: "pangeo-notebook=.* "
          replace: "pangeo-notebook=${{ steps.latest_version.outputs.version }} "

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update pangeo-notebook metapackage version to ${{ steps.latest_version.outputs.version }}"
          title: "Update pangeo-notebook metapackage version to ${{ steps.latest_version.outputs.version }}"
          reviewers: "scottyhq"
          branch: "upgrade-pangeo-metapackage-version"
          body: |
            A new pangeo-metapackage version has been detected.

            Updated `environment.yml`s to use `${{ steps.latest_version.outputs.version }}`.
